// Mocks generated by Mockito 5.4.6 from annotations
// in indulge/test/provider/sexual_event_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:indulge/data/models.dart' as _i4;
import 'package:indulge/data/repositories/sexual_event_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SexualEventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSexualEventRepository extends _i1.Mock
    implements _i2.SexualEventRepository {
  MockSexualEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.SexualEvent?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.SexualEvent?>.value(),
          )
          as _i3.Future<_i4.SexualEvent?>);

  @override
  _i3.Future<List<_i4.SexualEvent>> getByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getByDate, [date]),
            returnValue: _i3.Future<List<_i4.SexualEvent>>.value(
              <_i4.SexualEvent>[],
            ),
          )
          as _i3.Future<List<_i4.SexualEvent>>);

  @override
  _i3.Future<Map<DateTime, int>> getDailyEventCount() =>
      (super.noSuchMethod(
            Invocation.method(#getDailyEventCount, []),
            returnValue: _i3.Future<Map<DateTime, int>>.value(
              <DateTime, int>{},
            ),
          )
          as _i3.Future<Map<DateTime, int>>);

  @override
  _i3.Future<List<_i4.SexualEvent>> getAllEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvents, []),
            returnValue: _i3.Future<List<_i4.SexualEvent>>.value(
              <_i4.SexualEvent>[],
            ),
          )
          as _i3.Future<List<_i4.SexualEvent>>);

  @override
  _i3.Future<List<_i4.Location>> getAllLocations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLocations, []),
            returnValue: _i3.Future<List<_i4.Location>>.value(<_i4.Location>[]),
          )
          as _i3.Future<List<_i4.Location>>);

  @override
  _i3.Future<List<_i4.Person>> getPersonsFromActivity(
    _i4.SexualActivity? activity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonsFromActivity, [activity]),
            returnValue: _i3.Future<List<_i4.Person>>.value(<_i4.Person>[]),
          )
          as _i3.Future<List<_i4.Person>>);

  @override
  _i3.Future<List<_i4.Person>> getPersonsFromActivities(
    List<_i4.SexualActivity>? activities,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonsFromActivities, [activities]),
            returnValue: _i3.Future<List<_i4.Person>>.value(<_i4.Person>[]),
          )
          as _i3.Future<List<_i4.Person>>);

  @override
  _i3.Future<List<_i4.SexualActivityType>> getAllSexualActivityTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSexualActivityTypes, []),
            returnValue: _i3.Future<List<_i4.SexualActivityType>>.value(
              <_i4.SexualActivityType>[],
            ),
          )
          as _i3.Future<List<_i4.SexualActivityType>>);

  @override
  _i3.Future<List<_i4.SexualActivityTypeProperty>>
  getAllSexualActivityTypeProperties() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSexualActivityTypeProperties, []),
            returnValue: _i3.Future<List<_i4.SexualActivityTypeProperty>>.value(
              <_i4.SexualActivityTypeProperty>[],
            ),
          )
          as _i3.Future<List<_i4.SexualActivityTypeProperty>>);

  @override
  _i3.Future<List<_i4.SexualActivityType>> getSexualActivityTypesByIds(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSexualActivityTypesByIds, [ids]),
            returnValue: _i3.Future<List<_i4.SexualActivityType>>.value(
              <_i4.SexualActivityType>[],
            ),
          )
          as _i3.Future<List<_i4.SexualActivityType>>);

  @override
  _i3.Future<void> save(_i4.SexualEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#save, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SexualActivityTypeProperty>>
  getSexualActivityTypePropertiesForParticipant(
    _i4.SexualActivityParticipant? participant,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSexualActivityTypePropertiesForParticipant, [
              participant,
            ]),
            returnValue: _i3.Future<List<_i4.SexualActivityTypeProperty>>.value(
              <_i4.SexualActivityTypeProperty>[],
            ),
          )
          as _i3.Future<List<_i4.SexualActivityTypeProperty>>);

  @override
  _i3.Future<void> removeActivityByTypeId(
    String? eventId,
    String? activityTypeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeActivityByTypeId, [
              eventId,
              activityTypeId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeParticipantById(String? eventId, String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipantById, [eventId, personId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Person>> getAllPersons() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPersons, []),
            returnValue: _i3.Future<List<_i4.Person>>.value(<_i4.Person>[]),
          )
          as _i3.Future<List<_i4.Person>>);

  @override
  _i3.Future<_i4.Person?> getPersonById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonById, [id]),
            returnValue: _i3.Future<_i4.Person?>.value(),
          )
          as _i3.Future<_i4.Person?>);

  @override
  _i3.Future<void> savePerson(_i4.Person? person) =>
      (super.noSuchMethod(
            Invocation.method(#savePerson, [person]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Person?> getMyself() =>
      (super.noSuchMethod(
            Invocation.method(#getMyself, []),
            returnValue: _i3.Future<_i4.Person?>.value(),
          )
          as _i3.Future<_i4.Person?>);

  @override
  _i3.Future<void> deletePerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePerson, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> replacePersonInAllEvents(
    String? oldPersonId,
    String? newPersonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replacePersonInAllEvents, [
              oldPersonId,
              newPersonId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveActivityType(_i4.SexualActivityType? activityType) =>
      (super.noSuchMethod(
            Invocation.method(#saveActivityType, [activityType]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteActivityType(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActivityType, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isActivityTypeUsed(String? activityTypeId) =>
      (super.noSuchMethod(
            Invocation.method(#isActivityTypeUsed, [activityTypeId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> saveActivityProperty(
    _i4.SexualActivityTypeProperty? property,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveActivityProperty, [property]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteActivityProperty(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActivityProperty, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isActivityPropertyUsed(String? propertyId) =>
      (super.noSuchMethod(
            Invocation.method(#isActivityPropertyUsed, [propertyId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
