// Mocks generated by Mockito 5.4.6 from annotations
// in indulge/test/view/analysis/utils/analysis_calculator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:indulge/data/models.dart' as _i2;
import 'package:indulge/provider/sexual_event_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocation_0 extends _i1.SmartFake implements _i2.Location {
  _FakeLocation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SexualEventsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSexualEventsProvider extends _i1.Mock
    implements _i3.SexualEventsProvider {
  MockSexualEventsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> get ready =>
      (super.noSuchMethod(
            Invocation.getter(#ready),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(this, Invocation.getter(#ready)),
            ),
          )
          as _i4.Future<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> refreshAllData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAllData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void selectDate(DateTime? date) => super.noSuchMethod(
    Invocation.method(#selectDate, [date]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> selectEvent(_i2.SexualEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#selectEvent, [event]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeActivity(_i2.EventActivity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#removeActivity, [activity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeParticipant(_i2.Person? participant) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [participant]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeActivityFromEdit(String? activityCategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeActivityFromEdit, [activityCategoryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeParticipantFromEdit(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipantFromEdit, [personId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i2.SexualActivity> getSexualActivitiesForPersonAndActivity(
    _i2.Person? person,
    _i2.EventActivity? activity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSexualActivitiesForPersonAndActivity, [
              person,
              activity,
            ]),
            returnValue: <_i2.SexualActivity>[],
          )
          as List<_i2.SexualActivity>);

  @override
  _i4.Future<List<_i2.Person>> getPersonsForEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonsForEvent, [eventId]),
            returnValue: _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
          )
          as _i4.Future<List<_i2.Person>>);

  @override
  _i4.Future<List<_i2.Person>> getPersonsForActivity(
    _i2.EventActivity? activity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonsForActivity, [activity]),
            returnValue: _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
          )
          as _i4.Future<List<_i2.Person>>);

  @override
  _i4.Future<List<_i2.Person>> getAllPersons() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPersons, []),
            returnValue: _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
          )
          as _i4.Future<List<_i2.Person>>);

  @override
  _i4.Future<_i2.Person?> getPersonById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonById, [id]),
            returnValue: _i4.Future<_i2.Person?>.value(),
          )
          as _i4.Future<_i2.Person?>);

  @override
  _i4.Future<void> savePerson(_i2.Person? person) =>
      (super.noSuchMethod(
            Invocation.method(#savePerson, [person]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePerson, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveEvent(_i2.SexualEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#saveEvent, [event]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [eventId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.SexualEvent>> getAllEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvents, []),
            returnValue: _i4.Future<List<_i2.SexualEvent>>.value(
              <_i2.SexualEvent>[],
            ),
          )
          as _i4.Future<List<_i2.SexualEvent>>);

  @override
  _i4.Future<void> saveActivityCategory(
    _i2.SexualActivityCategory? activityCategory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveActivityCategory, [activityCategory]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteActivityCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActivityCategory, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isActivityCategoryUsed(String? activityCategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#isActivityCategoryUsed, [activityCategoryId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getUsageCountForCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUsageCountForCategory, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> saveSexualActivity(_i2.SexualActivity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#saveSexualActivity, [activity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSexualActivity(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSexualActivity, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isSexualActivityUsed(String? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#isSexualActivityUsed, [activityId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getUsageCountForActivity(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUsageCountForActivity, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.Location> createLocationFromCoordinates(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLocationFromCoordinates, [
              latitude,
              longitude,
            ]),
            returnValue: _i4.Future<_i2.Location>.value(
              _FakeLocation_0(
                this,
                Invocation.method(#createLocationFromCoordinates, [
                  latitude,
                  longitude,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Location>);

  @override
  _i4.Future<void> attachLocationToSelectedEvent(_i2.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#attachLocationToSelectedEvent, [location]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeLocationFromSelectedEvent() =>
      (super.noSuchMethod(
            Invocation.method(#removeLocationFromSelectedEvent, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
