// Mocks generated by Mockito 5.4.6 from annotations
// in indulge/test/view/analysis/utils/analysis_calculator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:indulge/data/models.dart' as _i6;
import 'package:indulge/provider/event_state.dart' as _i2;
import 'package:indulge/provider/sexual_event_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEventState_0 extends _i1.SmartFake implements _i2.EventState {
  _FakeEventState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SexualEventsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSexualEventsProvider extends _i1.Mock
    implements _i3.SexualEventsProvider {
  MockSexualEventsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> get ready =>
      (super.noSuchMethod(
            Invocation.getter(#ready),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(this, Invocation.getter(#ready)),
            ),
          )
          as _i4.Future<String>);

  @override
  _i2.EventState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeEventState_0(this, Invocation.getter(#state)),
          )
          as _i2.EventState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void selectDate(DateTime? date) => super.noSuchMethod(
    Invocation.method(#selectDate, [date]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> selectEvent(_i6.SexualEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#selectEvent, [event]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeActivity(_i6.EventActivity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#removeActivity, [activity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeParticipant(_i6.Person? participant) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [participant]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeActivityFromEdit(String? activityCategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeActivityFromEdit, [activityCategoryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeParticipantFromEdit(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipantFromEdit, [personId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i6.SexualActivity> getSexualActivitiesForPersonAndActivity(
    _i6.Person? person,
    _i6.EventActivity? activity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSexualActivitiesForPersonAndActivity, [
              person,
              activity,
            ]),
            returnValue: <_i6.SexualActivity>[],
          )
          as List<_i6.SexualActivity>);

  @override
  _i4.Future<List<_i6.Person>> getPersonsForEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonsForEvent, [eventId]),
            returnValue: _i4.Future<List<_i6.Person>>.value(<_i6.Person>[]),
          )
          as _i4.Future<List<_i6.Person>>);

  @override
  _i4.Future<List<_i6.Person>> getPersonsForActivity(
    _i6.EventActivity? activity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonsForActivity, [activity]),
            returnValue: _i4.Future<List<_i6.Person>>.value(<_i6.Person>[]),
          )
          as _i4.Future<List<_i6.Person>>);

  @override
  _i4.Future<List<_i6.Person>> getAllPersons() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPersons, []),
            returnValue: _i4.Future<List<_i6.Person>>.value(<_i6.Person>[]),
          )
          as _i4.Future<List<_i6.Person>>);

  @override
  _i4.Future<_i6.Person?> getPersonById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonById, [id]),
            returnValue: _i4.Future<_i6.Person?>.value(),
          )
          as _i4.Future<_i6.Person?>);

  @override
  _i4.Future<void> savePerson(_i6.Person? person) =>
      (super.noSuchMethod(
            Invocation.method(#savePerson, [person]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePerson, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveEvent(_i6.SexualEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#saveEvent, [event]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [eventId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.SexualEvent>> getAllEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvents, []),
            returnValue: _i4.Future<List<_i6.SexualEvent>>.value(
              <_i6.SexualEvent>[],
            ),
          )
          as _i4.Future<List<_i6.SexualEvent>>);

  @override
  _i4.Future<void> saveActivityCategory(
    _i6.SexualActivityCategory? activityCategory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveActivityCategory, [activityCategory]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteActivityCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActivityCategory, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isActivityCategoryUsed(String? activityCategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#isActivityCategoryUsed, [activityCategoryId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> saveSexualActivity(_i6.SexualActivity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#saveSexualActivity, [activity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSexualActivity(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSexualActivity, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isSexualActivityUsed(String? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#isSexualActivityUsed, [activityId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
